version: "3.2"

services:
  lockbox:
    build: ./lockbox
    image: docker-registry.i.mm12.xyz/nffu-lockbox:0.0.0
    expose:
        - "80"
    secrets:
      - lockbox-credential-key
  fenetre:
    build: ./fenetre
    image: docker-registry.i.mm12.xyz/nffu-fenetre:0.0.0
    ports:
        - "8083:8080"
    volumes:
        - type: bind
          source: ./fenetre/fenetre
          target: /opt/venv/lib/python3.7/site-packages/fenetre
    environment:
        - "QUART_DEBUG=1"
  db:
    image: mongo
    volumes:
        - db-data:/data/db
    deploy:
        resources:
            limits:
                cpus: '0.1'
                memory: 64M

secrets:
  lockbox-credential-key:
    file: lockbox-credential-key
    # external: true

volumes:
  lockbox-data:
  db-data:
