version: "3.7"

services:
  lockbox:
    build: ./lockbox
    image: docker-registry.i.mm12.xyz/nffu-lockbox:dev
    init: true
    ports:
      - "8082:80"
    volumes:
      - type: bind
        source: ./lockbox/lockbox
        target: /opt/venv/lib/python3.7/site-packages/lockbox
    secrets:
      - lockbox-credential-key
    environment:
      - LOCKBOX_CREDENTIAL_KEY_FILE=/run/secrets/lockbox-credential-key
      - LOCKBOX_DEBUG=1
      - LOCKBOX_SCHOOL=1276
  fenetre:
    build: ./fenetre
    image: docker-registry.i.mm12.xyz/nffu-fenetre:dev
    ports:
      - "8083:8080"
    volumes:
      - type: bind
        source: ./fenetre/fenetre
        target: /opt/venv/lib/python3.7/site-packages/fenetre
    environment:
      - "QUART_DEBUG=1"
  db:
    image: mongo:4.4
    volumes:
      - db-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 64M
    command: --quiet --nojournal --wiredTigerCacheSizeGB 0.05 --setParameter diagnosticDataCollectionEnabled=false
    logging:
      driver: none

secrets:
  lockbox-credential-key:
    file: lockbox-credential-key
    # external: true

volumes:
  db-data:
