version: "3.2"

services:
  lockbox:
    build: ./lockbox
    image: docker-registry.i.mm12.xyz/nffu-lockbox:0.0.0
    expose:
      - "80"
    secrets:
      - lockbox-credential-key

secrets:
  lockbox-credential-key:
    external: true

volumes:
  lockbox-data:
